### ISSUE TITLE
[typed-protocols]: Fix the contra-tracer mess

### ISSUE THREAD

**Issue by erikd** [input-output-hk/typed-protocols#38]
Part of https://github.com/input-output-hk/devx-aux/issues/42

**Comment by coot** [comment]
Fixed in #37, isn't it? If not reopen.

**Comment by erikd** [comment]
@Coot The mess is far far far bigger than that.

Renaming IOG's contra-tracer to iog-contra-tracer and propagating this through all the repos is incredibly difficult.
The problems include:

* `contra-tracer` is used everywhere.
* The Hackage version and the IOG version have the same package name, define the same module names but are not 100% compatible.
* Some code in `ouroboros-network` is designed to be compatible with both the Hackage of the IOG version.
* `node` uses a non-head version of `ouroboros-network` that includes `ouroboros-consensus`.
* Current HEAD of `ouroboros-network` does not include `ouroboros-consensus`.

**Comment by erikd** [comment]
PR is https://github.com/input-output-hk/typed-protocols/pull/39

**Comment by erikd** [comment]
Done!
